package commands

import (
	"encoding/json"
	"strings"
)

// Per-host renderers turn garminctl's small mutation-vector set into safety config. Each emits
// Bash permission patterns; claude-code additionally emits the enforcing PreToolUse hook. The
// permission rules are coarse literal prefixes (belt-and-suspenders); only the hook defeats
// obfuscation, path-prefixed invocations, and the method-gated `api` hatch.

// renderClaudeCode emits the Claude Code guard: a PreToolUse hook script (the enforcement
// layer) plus a settings.json fragment with deny/ask/allow rules and the hook wiring.
func renderClaudeCode() (string, error) {
	deny := make([]string, 0, len(blockedBashPaths))
	for _, p := range blockedBashPaths {
		deny = append(deny, bashPattern(p))
	}
	// The raw `api` hatch can carry a write method; the coarse prefix layer can't inspect the
	// method, so it asks for approval and the hook makes the precise read/write decision.
	ask := []string{bashPattern("api")}
	// Every other garminctl subcommand is a read.
	allow := []string{"Bash(garminctl:*)"}

	// ${CLAUDE_PROJECT_DIR} is the Claude runtime variable; Claude substitutes it when loading
	// the hook — it is NOT expanded here.
	hookPath := "${CLAUDE_PROJECT_DIR}/.claude/hooks/garminctl-guard.sh"
	hookEntry := func(matcher string) map[string]any {
		return map[string]any{
			"matcher": matcher,
			"hooks":   []any{map[string]any{"type": "command", "command": hookPath}},
		}
	}
	settings := map[string]any{
		"permissions": map[string]any{
			"deny":  deny,
			"ask":   ask,
			"allow": allow,
		},
		"hooks": map[string]any{
			// Hook both the Bash surface and the garminctl MCP namespace.
			"PreToolUse": []any{hookEntry("Bash"), hookEntry("mcp__garminctl__")},
		},
		"_comment": "Generated by `garminctl agent guard --host claude-code`. Save the hook script above to " +
			".claude/hooks/garminctl-guard.sh (chmod +x) and merge this fragment into .claude/settings.json. " +
			"deny = auth logout + alias set; ask = the raw api hatch (hook blocks write methods); allow = reads. " +
			"MCP-only operation is the hard guarantee.",
	}
	b, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return "", err
	}

	var out strings.Builder
	out.WriteString("# ----- .claude/hooks/garminctl-guard.sh (save + chmod +x) -----\n")
	out.WriteString(hookScript())
	out.WriteString("\n# ----- merge into .claude/settings.json -----\n")
	out.Write(b)
	out.WriteString("\n")
	return out.String(), nil
}

// hookScript generates the PreToolUse hook. Blocked commands are matched by exact SUBCOMMAND
// PATH at the command position — never by bare verbs anywhere in the line — with an optional
// path prefix before the binary so ./bin/garminctl and /usr/local/bin/garminctl are caught too.
// The raw `garminctl api` hatch is gated by HTTP METHOD: a call with -X/--method POST|PUT|
// DELETE|PATCH is blocked; GET (the default) is a read and passes.
func hookScript() string {
	var cliArray strings.Builder
	cliArray.WriteString("blocked_cmds=(\n")
	for _, p := range blockedBashPaths {
		safe := strings.ReplaceAll(p, "'", "'\\''")
		cliArray.WriteString("  '" + safe + "'\n")
	}
	cliArray.WriteString(")")

	return `#!/usr/bin/env bash
# garminctl agent guard — blocks the mutation vectors on the Bash and MCP surfaces.
# Generated by ` + "`garminctl agent guard`" + `; regenerate after upgrading garminctl.
#
# MATCHING STRATEGY: blocked commands (auth logout, alias set) are matched by exact
# SUBCOMMAND PATH at the command position, not by bare verbs anywhere in the line, so
#   garminctl config use "notes about auth logout"
# is NOT blocked. For each blocked path P the CLEANED command is tested against:
#   (^|[;&|([:space:]]+)([^[:space:]]*/)?garminctl[[:space:]]+<P>([[:space:];&|)]|$)
# The optional ([^[:space:]]*/)? prefix catches path-invoked binaries like ./bin/garminctl
# or /usr/local/bin/garminctl, while a different binary ending in "garminctl" (mygarminctl)
# is NOT matched.
#
# The raw "garminctl api <path>" hatch is gated by HTTP METHOD: an invocation carrying
# -X/--method POST|PUT|DELETE|PATCH is the only way to mutate Garmin data and is blocked;
# a GET (the default) is a read and passes. A --data value that merely contains "delete"
# is not affected.
#
# De-obfuscation: quotes (\042 / \047) and backslash (\134) are stripped before matching to
# defeat tricks like: garminctl auth log""out. Variable indirection and shell aliases are NOT
# defeated — use MCP-only mode for a hard guarantee.

# --- blocked command paths (Bash surface) ---
` + cliArray.String() + `

# --- blocked MCP tool names (exact); garminctl's MCP surface is read-only, so none ---
blocked_tools=(
)

input=$(cat)

# deny_raw emits a denial with a FIXED reason via printf (no jq needed).
deny_raw() {
  printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"%s"}}\n' "$1"
  exit 0
}

# deobfuscate strips quote chars (\042=", \047=', \134=\) and collapses newlines so a token
# cannot be split across lines.
deobfuscate() {
  printf '%s' "$1" | tr -d '\042\047\134' | tr '\n' ' '
}

# bash_is_blocked returns 0 (true) if the cleaned command contains a blocked garminctl
# subcommand path at the command position. Between the binary and the subcommand only the
# KNOWN global flags may appear (garminctl --profile juan auth logout), matched by ${gap}.
# Limiting the gap to real flags — not an arbitrary .* — keeps a subcommand VALUE that merely
# contains the words (garminctl config use "notes about auth logout") from matching.
bash_is_blocked() {
  local cleaned="$1"
  # Global flags that may sit before the subcommand: --profile/-p, --output/-o take a value;
  # --no-color/--dry-run are booleans.
  local gap='([[:space:]]+(--profile|-p|--output|-o)([[:space:]]+|=)[^[:space:]]+|[[:space:]]+(--no-color|--dry-run))*'
  local p
  for p in "${blocked_cmds[@]}"; do
    local pat
    pat=$(printf '%s' "$p" | sed 's/ /[[:space:]]+/g')
    if printf '%s' "$cleaned" | grep -qiE "(^|[;&|([:space:]]+)([^[:space:]]*/)?garminctl${gap}[[:space:]]+${pat}([[:space:];&|)]|\$)"; then
      return 0
    fi
  done
  return 1
}

# api_is_blocked returns 0 (true) when the raw "garminctl api" hatch is invoked with a write
# HTTP method. The three conditions must all hold: a garminctl invocation at a command
# position, the "api" subcommand token, and a -X/--method write verb.
api_is_blocked() {
  local cleaned="$1"
  printf '%s' "$cleaned" | grep -qiE "(^|[;&|([:space:]]+)([^[:space:]]*/)?garminctl[[:space:]]" || return 1
  printf '%s' "$cleaned" | grep -qiE "[[:space:]]api([[:space:]]|\$)" || return 1
  if printf '%s' "$cleaned" | grep -qiE "(-X|--method)[[:space:]]*=?[[:space:]]*(POST|PUT|DELETE|PATCH)"; then
    return 0
  fi
  return 1
}

# Without jq we cannot isolate the tool_name/command fields. Fail safe: flatten the JSON
# structure chars and apply the same de-obfuscation + anchored matching on the raw payload.
if ! command -v jq >/dev/null 2>&1; then
  flat=$(printf '%s' "$input" | tr '\n{}:,' '     ')
  cleaned=$(deobfuscate "$flat")
  if bash_is_blocked "$cleaned"; then
    deny_raw "garminctl agent guard: blocked operation (jq unavailable; raw match)."
  fi
  if api_is_blocked "$cleaned"; then
    deny_raw "garminctl agent guard: raw api write blocked (jq unavailable; raw match)."
  fi
  exit 0
fi

# deny emits the denial with a jq-escaped reason so an interpolated value can never break out
# of the JSON string.
deny() {
  jq -c -n --arg r "$1" \
    '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"deny",permissionDecisionReason:$r}}'
  exit 0
}

tool=$(printf '%s' "$input" | jq -r '.tool_name // empty')
case "$tool" in
  Bash)
    raw_cmd=$(printf '%s' "$input" | jq -r '.tool_input.command // empty')
    cleaned=$(deobfuscate "$raw_cmd")
    if bash_is_blocked "$cleaned"; then
      deny "garminctl agent guard: blocked operation (auth logout / alias set)."
    fi
    if api_is_blocked "$cleaned"; then
      deny "garminctl agent guard: raw api write blocked (only GET reads pass). Use dedicated commands or MCP-only mode."
    fi
    ;;
  *)
    # MCP branch: exact set-membership — no substring or regex match.
    for t in "${blocked_tools[@]}"; do
      if [ "$tool" = "$t" ]; then
        deny "garminctl agent guard: blocked MCP tool (${tool})."
      fi
    done
    ;;
esac
exit 0
`
}

// renderCodex emits a Codex config.toml: a read-only sandbox with approvals required, plus a
// commented list of the mutation vectors a reviewer should never auto-approve.
func renderCodex() (string, error) {
	var b strings.Builder
	b.WriteString("# Generated by `garminctl agent guard --host codex`.\n")
	b.WriteString("# Read-only sandbox: garminctl reads run freely; the mutation vectors require approval.\n")
	// Codex reads TOP-LEVEL sandbox_mode/approval_policy keys; an invented [sandbox] table is
	// silently ignored.
	b.WriteString("approval_policy = \"on-request\"\n")
	b.WriteString("sandbox_mode = \"read-only\"\n\n")
	b.WriteString("# Never auto-approve these garminctl operations:\n")
	b.WriteString("#   garminctl auth logout          (deletes the stored session)\n")
	b.WriteString("#   garminctl alias set ...        (can mint a shorthand for a blocked command)\n")
	b.WriteString("#   garminctl api <path> -X POST|PUT|DELETE|PATCH   (raw mutation of Garmin data)\n")
	b.WriteString("#\n")
	b.WriteString("# Reads — every resource, every `connect` endpoint, and `garminctl api` GET — are safe.\n")
	return b.String(), nil
}

// renderOpenCode emits an opencode.json permission map: deny the blocked paths, ask the raw
// api hatch, allow reads — keyed by the Bash command patterns OpenCode matches.
func renderOpenCode() (string, error) {
	perms := map[string]string{}
	for _, p := range blockedBashPaths {
		perms[bashPattern(p)] = "deny"
	}
	perms[bashPattern("api")] = "ask"
	perms["Bash(garminctl:*)"] = "allow"
	root := map[string]any{
		"$schema":    "https://opencode.ai/config.json",
		"permission": perms,
		"_comment": "Generated by `garminctl agent guard --host opencode`. Merge into opencode.json. " +
			"deny = auth logout + alias set; ask = the raw api hatch; allow = reads. These are literal " +
			"prefix rules — for obfuscation-resistant blocking and method-gated api use --host claude-code.",
	}
	b, err := json.MarshalIndent(root, "", "  ")
	if err != nil {
		return "", err
	}
	return string(b) + "\n", nil
}
